movieticketbooking/Admin/urls.py
from django.urls import path
from Admin import views


urlpatterns = [
    path('retrieve_path/', views.index),
    path('create_path/', views.create),
    path('edit_path/<int:p_id>', views.edit),
    path('update_path/<int:p_id>', views.update),
    path('delete_path/<int:d_id>', views.delete)
]

movieticketbooking/movies/urls.py
from django.urls import path
from movies import views


urlpatterns = [
    path('retrieve_path/', views.index),
    path('add_movie/', views.create),
    path('edit_movie/<int:m_id>', views.edit),
    path('update_movie/<int:p_id>', views.update),
    path('delete_movie/<int:id>', views.delete),
    path('moviepage_retrieve/', views.datamovie)
   # path('ticketpage_retrieve/<int:c_id>', views.ticketmovie)

]

movieticketbooking/movieticketbooking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('customers/', include('customers.urls')),
    path('homepage/', include('homepage.urls')),
    path('Booking/', include('Booking.urls')),
    path('Admin/', include('Admin.urls')),
]

movieticketbooking/movies/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    Id = models.AutoField(auto_created=True, primary_key=True)
    Name =models.CharField(max_length=200)
    class meta:
        db_table = "movie"

movieticketbooking/movies/forms.py
from django import forms
from movies.models import movie
class movieForms(forms.ModelForm):
    class Meta:
        model = movie
        fields = "__all__"

movieticketbooking/movies/views.py
from django.shortcuts import render, redirect
from movies.models import movie
from movies.forms import movieForms


# Creating  views for retreiving data.
def index(request):
    data = movie.objects.all()
    return render(request, "movies/retrieve.html", {'table_data': data})

# Creating  views for retreiving data in movie page
def datamovie(request):
    data = movie.objects.all()
    return render(request, "homepage/movies.html", {'table_data': data})



# Creating  views for creating data.
def create(request):
    if request.method == "POST":
        print(request.POST)
        form = movieForms(request.POST)
        form.save()
        return redirect("/movies/retrieve_path/")
    else:
        form = movieForms()
    return render(request, "movies/create.html", {'forms': form})


# creating function for edit
def edit(request, m_id):
    try:
        data = movie.objects.get(Id=m_id)
        return render(request, "movies/edit.html", {'values': data})
    except:
        print("no data")
        return redirect("/movies/retrieve_path")


# creating function for update
def update(request, p_id):
    data = movie.objects.get(Id=p_id)
    form = movieForms(request.POST, instance=data)
    if form.is_valid():
        try:
            form.save()
            return redirect("/movies/retrieve_path")
        except:
            print("the form is invalid")
    return render(request, "movies/edit.html", {'values': data})


#creating function for delete button
def delete(request, id):
    try:
        value = movie.objects.get(Id=id)
        print(value)
        value.delete()
        return redirect("/movies/retrieve_path")
    except:
        print("no data")

movieticketbooking/templates/movies/create.html
{% extends "dashboard-layout.html" %}
{% block content %}
<div class="p-4">
    <a type="button" class="btn btn-primary btn-sm" href="/movies/retrieve_path/">Back</a>
    <form method="post" action="/movies/add_movie/">
    {% csrf_token %}
    <label for="moviename">Movie Name</label>
    <!--{{forms.Name}}-->
        <input type="text" name="Name" class="form-control d-inline" maxlength="200" required="" id="id_Name">
      <!--<input type="text" id="moviename" name="Name" value="">-->
    <button type="submit" class="btn btn-success mb-1 ml-2">Create</button>


 </form>
</div>

<script type="text/javascript">
    $(function(){
    $('.dashboardsidebar').find('.active').removeClass('active');
     $('#movies').addClass('active');
    });

</script>
{% endblock %}

movieticketbooking/templates/movies/edit.html
{% extends "dashboard-layout.html" %}
{% block content %}
<div class="p-4">
    <a type="button" class="btn btn-primary btn-sm mb-3" href="/movies/retrieve_path">back</a>
<form method="post" class="form-group" action="/movies/update_movie/{{values.Id}}">
    {% csrf_token %}
<label for="id_name" class="font-weight-bold" id="lblcs">Movie Name:</label>
    <input type="text" name="Name" class="form-control form-inline d-inline" id="edtsbmt" placeholder="Enter movie name" maxlength="200" value="{{values.Name}}" id="id_name">
   <input type="submit" class="btn btn-success  mb-1 mb-1 ml-3"  value="update">

</form>
</div>

<script type="text/javascript">
    $(function(){
    $('.dashboardsidebar').find('.active').removeClass('active');
     $('#movies').addClass('active');
    });

</script>

{% endblock %}

movieticketbooking/templates/movies/retrieve.html
{% extends "dashboard-layout.html" %}
{% block content %}
<div>
<a type="button" class=" btn btn-primary btn-sm my-2 p-2" href="/movies/add_movie/" >create</a>
<table class="table table-bordered table-hover table-striped">

    <tr>
        <th>Id</th>
        <th>Name</th>
         <th>Action</th>

        {% for i in table_data %}
        <tr>
            <td>{{i.Id}}</td>
            <td>{{i.Name}}</td>
            <th>
        <a type="button" class="btn btn-primary" href="/movies/edit_movie/{{i.Id}}">Edit</a>
        <a type="button" class="btn btn-danger" href="/movies/delete_movie/{{i.Id}}">Delete</a>
            </th>
        </tr>
    {% endfor %}

</table>
</div>

<script type="text/javascript">
    $(function(){
    $('.dashboardsidebar').find('.active').removeClass('active');
     $('#movies').addClass('active');
    });

</script>
{% endblock %}